### ISSUE TITLE
Namecoin Currency Transactions

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/BitcoinArmory#1]
Enable currency transactions (sending/receiving) for Namecoin.

**Comment by JeremyRand** [comment]
So, my understanding is that this is mostly working but we haven't gotten any test reports.  If anyone is able to post some test reports, that would be most welcome.

**Comment by josephbisch** [comment]
Jonasbits did test this and so have I, but it would be good to have more independent testing.

**Comment by JeremyRand** [comment]
Note: for this bounty to be claimed, the Namecoin port should be rebased on the latest Armory code (looks like the Namecoin port is about half a year old).
