### ISSUE TITLE
Fix Namecoin tests

### ISSUE THREAD

**Issue by josephbisch** [namecoin/BitcoinArmory#5]
The Namecoin tests are currently broken. Specificially [Load5Blocks](https://github.com/namecoin/BitcoinArmory/blob/c9f53d4ade258d19064f79b64ca138a47b414761/cppForSwig/gtest/NamecoinTests.cpp#L277) hangs (by hangs I mean when it gets to the Load5Blocks test, it starts the test and then appears to run indefinitely). To fix this issue, you should make it so that NamecoinTests runs to completion without hanging. The tests should also pass.

I think the issue has to do with the file [createTestChain.py in the extras directory](https://github.com/namecoin/BitcoinArmory/blob/30ba60bb4199856b1f4435ec3e384aa6c6e4f3ba/extras/createTestChain.py). I think this, because the actual code runs fine, it is just the tests that hang. The createTestChain.py script is used to generate the test blocks used by Load5Blocks. To use createTestChain.py, you should first copy it to the root of the BitcoinArmory code directory. Then change [this line](https://github.com/namecoin/BitcoinArmory/blob/30ba60bb4199856b1f4435ec3e384aa6c6e4f3ba/extras/createTestChain.py#L30) to `COIN = 'Namecoin'` and [the previous line](https://github.com/namecoin/BitcoinArmory/blob/30ba60bb4199856b1f4435ec3e384aa6c6e4f3ba/extras/createTestChain.py#L29) to `fakeBlocks=True`. Then you run createTestChain.py like `python createTestChain.py --namecoin`.

Work on the tests, build them, and then run the NamecoinTests binary from cppForSwig/gtest/. The file namecoinTestsLog.txt will contain the logs from the tests.

**Comment by JeremyRand** [comment]
Note: for this bounty to be claimed, the Namecoin port should be rebased on the latest Armory code (looks like the Namecoin port is about half a year old).
